name: notifyme
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  get: 4.6.6
  home_widget: 0.7.0
  workmanager: 0.5.2
  permission_handler: 11.3.1
  get_storage: 2.1.1
  get_cli: 1.8.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

